version: '3.7'
services:
  tg-bot-py:
    image: ${IMAGE}
    restart: unless-stopped
    container_name: tg-bot-py
    environment:
      - ENV_API_TOKEN=${TOKEN}
    networks:
      - mynet
  nginx:
    image: nginx:1.21
    depends_on:
      - tg-bot-py
    container_name: nginx-server
    restart: unless-stopped
    volumes:
     - ./nginx:/etc/nginx/conf.d
     - ./cert:/etc/nginx/cert
    ports:
     - 443:443
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
